config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  get 'customers/alphabetized', to: 'customers#alphabetized'
  get 'customers/missing_email', to: 'customers#missing_email'
  resources :customers, only: [:index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_one_attached :image
    validates :full_name, presence: true

    def self.ransackable_associations(auth_object = nil)
        ["image_attachment", "image_blob"]
    end
    
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer mb-10 p-5 bg-white rounded shadow-md flex items-center space-x-4 justify-center">
  
  <div>
    <p class="font-bold"><%= customer.full_name %></p>
    <p>Phone_Number: <%= customer.phone_number %></p>
    <p>Email: <%= customer.email_address %></p>
    <p>Notes: <%= customer.notes %></p>
    <% if customer.image.attached? %>
      <%= image_tag url_for(customer.image), class: "w-40 h-40 rounded-full" %>
    <% end %>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div>
 
  <h1 class="mb-10">Alphabetized Customers</h1>
  <%= render @customers %>
  <%= link_to "All Customers", customers_path %>
  <%= link_to "Missing Email", customers_missing_email_path %>

</div>

app/views/customers/index.html.erb
<div class="container font-bold">
  <h1 class="mb-10">All Customers</h1>
  <div class="customers flex flex-column mb-4  center">
    <%= render partial: "customer", collection: @customers %>
  </div>
  <div class="links">
    <%= link_to "Alphabetized", customers_alphabetized_path, class: "inline-block mr-6 text-blue-600 " %>
    <%= link_to "Missing Email", customers_missing_email_path, class: "inline-block text-blue-600 " %>
  </div>
</div>

app/views/customers/missing_email.html.erb
<div>
  <h1 class="mb-10">Customers Missing Email</h1>
  <%= render @customers %>
  <%= link_to "All Customers", customers_path %>
  <%= link_to "Alphabetized", customers_alphabetized_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>